### Find All Images
GET http://localhost:3000/api/image


### Create image
POST http://localhost:3000/api/image
Content-Type: application/json

{
    "tags": ["xxx", "yyy", 4354],
    "uri": "123",
    "category": "Animals"
}

### Update Image
PATCH http://localhost:3000/api/image/610bc0c2ce13ee0718955a71
Content-Type: application/json

{
    "category": "jhj"
}

### Delete Image
DELETE http://localhost:3000/api/image/delete/610c32ecb6a89d3f78592362


###
POST http://localhost:3000/api/image/?id=32053209
Content-Type: application/json

{
    "xx": "xx"
}