### Find All Images
GET http://localhost:3000/image


### Create image
POST http://localhost:3000/image
Content-Type: application/json

{
    "tags": ["xxx", "yyy", 4354],
    "uri": "123",
    "category": "Animals"
}

### Update Image
PATCH http://localhost:3000/image/610bc0c2ce13ee0718955a71
Content-Type: application/json

{
    "category": "jhj"
}
