### Register
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Haha",
    "email": "hehe@gmail.com",
    "password": "1234"
}

### Login (Get JWT Token)
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "Haha",
    "password": "1234"
}

